# Generated by Django 6.0.7 on 2026-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Italia', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Se attivo, altri utenti potranno vedere la tua posizione per scambi a mano o valutare le spese di spedizione'),
        ),
    ]
