# Generated by Django 6.0.7 on 2026-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_province_alter_user_allow_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Se spuntato, gli altri utenti potranno vedere la tua posizione'),
        ),
    ]
