# Generated by Django 6.0.7 on 2026-08-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection_public',
            field=models.BooleanField(default=False, help_text='Se spuntato, chiunque potrà vedere la tua collezione dal tuo profilo pubblico'),
        ),
    ]
