# Generated by Django 6.0.7 on 2026-07-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_ownedcard_card_type_ownedcard_grade_and_more'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owned_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cards.ownedcard'),
        ),
    ]
