# Generated by Django 6.0.7 on 2026-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_listing_owned_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
