# Generated by Django 6.0.7 on 2026-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_offer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('fixed', 'Prezzo fisso'), ('auction', 'Asta')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('offer', 'Offerta'), ('message', 'Messaggio'), ('bid', 'Rilancio')], default='offer', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='carrier',
            field=models.CharField(blank=True, choices=[('brt', 'BRT'), ('dhl', 'DHL'), ('poste', 'Poste Italiane'), ('gls', 'GLS')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
