# Generated by Django 6.0.7 on 2026-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_listing_auction_closed_listing_auction_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
