# Generated by Django 6.0.7 on 2026-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_listing_price_alter_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('fixed', 'Compra Subito'), ('auction', 'Asta')], default='fixed', max_length=10),
        ),
    ]
