# Generated by Django 6.0.7 on 2026-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_game_expansion_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedcard',
            name='card_type',
            field=models.CharField(choices=[('raw', 'Raw'), ('graded', 'Graded')], default='raw', max_length=10),
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='grading_company',
            field=models.CharField(blank=True, choices=[('PSA', 'PSA'), ('BGS', 'Beckett (BGS)'), ('CGC', 'CGC'), ('SGC', 'SGC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ownedcard',
            name='condition',
            field=models.CharField(blank=True, choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], max_length=10),
        ),
    ]
