# Generated by Django 6.0.7 on 2026-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_ownedcard_market_value_ownedcard_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cards/games/'),
        ),
        migrations.AlterField(
            model_name='ownedcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/owned/'),
        ),
    ]
