# Generated by Django 6.0.7 on 2026-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_game_logo_alter_ownedcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedcard',
            name='language',
            field=models.CharField(default='Italiano', max_length=30),
        ),
    ]
